// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_reach_100_points = "CgkI1fvWjqUXEAIQAg"; // <GPGSID>
        public const string leaderboard_highscore = "CgkI1fvWjqUXEAIQAQ"; // <GPGSID>
        public const string achievement_your_first_cosmetic = "CgkI1fvWjqUXEAIQAw"; // <GPGSID>
        public const string achievement_first_stop = "CgkI1fvWjqUXEAIQBw"; // <GPGSID>
        public const string achievement_wow_500_points = "CgkI1fvWjqUXEAIQBA"; // <GPGSID>
        public const string achievement_yas_my_queen = "CgkI1fvWjqUXEAIQBg"; // <GPGSID>
        public const string achievement_credit_your_mates = "CgkI1fvWjqUXEAIQCA"; // <GPGSID>

}

